# Stone V4 - Data Science

**Prof.:** Gabriel R. Freitas \
**E-mail:** gab.ribeiro.freitas@gmail.com\
**LinkedIn:** www.linkedin.com/in/grfreitas/

# Lista de Exercícios - Numpy

---

##### 0. Importe a biblioteca numpy como np

In [1]:
import numpy as np

##### 1. Crie um array de zeros de tamanho 10

In [7]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##### 2. Altere o array criado no item 1 para que o quinto valor seja 1

In [8]:
zeros[4] = 1
zeros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

##### 3. Crie um array de valores entre 10 e 50

In [12]:
array = np.arange(10, 51, 1)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

##### 4. Inverta o array criado no item 3 (o último elemento se torna o primeiro elemento).

In [16]:
invertido = array[::-1]
invertido

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

##### 5. Crie uma matriz 3x3 com valores entre 0 e 8

In [19]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. Crie uma matriz 3x3x3 de valores aleatórios e ache seu valor máximo e mínimo.

In [26]:
matriz = np.random.rand(3, 3, 3)
matriz

array([[[0.33231679, 0.75806347, 0.57588976],
        [0.49357168, 0.08608295, 0.01261087],
        [0.58814263, 0.56887639, 0.50596785]],

       [[0.86388083, 0.1127942 , 0.25530599],
        [0.9714552 , 0.34412314, 0.75076383],
        [0.69942498, 0.21350252, 0.8364409 ]],

       [[0.51210733, 0.86907662, 0.83536133],
        [0.27411618, 0.40348644, 0.60849901],
        [0.21837127, 0.69671397, 0.03465662]]])

In [24]:
matriz.max()

0.9484637897974376

In [25]:
matriz.min()

0.029411737132453597

##### 7. Crie um array de zeros 10x10 onde os valores da borda matriz são iguais a 1

In [37]:
borda = np.zeros((10, 10))

In [38]:
borda[0] = 1
borda[-1] = 1
borda[:, 0] = 1
borda[:, -1] = 1

In [39]:
borda

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

##### 8. Crie uma matriz 8x8 e preencha com um padrão de xadrez (1 e 0 intercalados)

In [63]:
zeros = np.zeros((8, 8))

In [66]:
zeros[::2, ::2] = 1

In [68]:
zeros[1::2, 1::2] = 1

In [69]:
zeros

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

##### 9. Crie um array de números inteiros aleatórios entre 1 e 50. A partir dele, crie um array dos valores pares e outro array dos ímpares.

In [3]:
import numpy as np

In [4]:
array = np.random.randint(10, 50, 10)

In [6]:
array

array([21, 15, 32, 13, 19, 16, 34, 37, 33, 41])

In [5]:
pares = array[array % 2 == 0]
impares = array[array % 2 == 1]

In [77]:
pares

array([38, 40, 12, 38, 12, 48])

In [78]:
impares

array([39, 33, 17, 21])

##### 10. Crie ume função que receba um array e retorne o array standardizado¹. Teste a função em um array qualquer.

- 1. Standardização: (Array - Valor Médio do Array) / Desvio Padrão do Array

In [79]:
def standardize(array):
    return (array - array.mean()) / array.std()

In [80]:
standardize(pares)

array([ 0.47351372,  0.61556784, -1.3731898 ,  0.47351372, -1.3731898 ,
        1.18378431])

---