# Stone V4 - Data Science

---

**Data:** 14/09/2021 \
**Prof.:** Gabriel R. Freitas \
**E-mail:** gab.ribeiro.freitas@gmail.com\
**LinkedIn:** www.linkedin.com/in/grfreitas/

### Revisão

#### List Comprehension

In [42]:
lista = [1, 2, 3, 4, 5, 6]
# retorno = [1, 4, 9, 16, 25]

##### Exemplo 1

In [43]:
# Maneira 1 - For clássico
lista_vazia = []
for valor in lista:
    lista_vazia.append(valor ** 2)

In [44]:
print(lista)

[1, 2, 3, 4, 5, 6]


In [45]:
print(lista_vazia)

[1, 4, 9, 16, 25, 36]


In [46]:
lista

[1, 2, 3, 4, 5, 6]

In [47]:
# Maneira 2 - List Comprehension
[valor ** 2 for valor in lista]

[1, 4, 9, 16, 25, 36]

##### Exemplo 2

In [48]:
lista

[1, 2, 3, 4, 5, 6]

In [55]:
# Maneira 1 - For clássico
lista_vazia = []
for valor in lista:
    if valor % 2 == 0:
        lista_vazia.append(valor ** 2)

In [68]:
# Maneira 2 - List Comprehension
[valor ** 2 for valor in lista if valor % 2 == 1]

[1, 9, 25]

In [69]:
# Com else
[valor ** 2 if valor % 2 == 0 else 0 for valor in lista]

[0, 4, 0, 16, 0, 36]

---

### Exercício

In [ ]:
valores = tuple(int(input('Digite valores '))for c in range(1, 5))

In [75]:
print(f'O numero nove aparece {valores.count(4)} vezes')

O numero nove aparece 1 vezes


In [ ]:
print(f'Valor 3 foi digitado pela primeira vez na {valores.index(3)+1}º posição' if 3 in valores else 'Não foi digitado valor 3')

In [ ]:
print('Valores pares digitados foram', end=' ')

In [83]:
{n for n in valores if n % 2 == 0}

{2, 4}

In [84]:
[n for n in valores if n % 2 == 0]

[2, 4]

In [91]:
tuple(n for n in valores if n % 2 == 0)

(2, 4)

# Aula 3 - Numpy

In [93]:
# Numerical Python
# Biblioteca de manipulação de arrays que se baseia principalmente em álgebra linear!
import numpy as np

In [104]:
# criando listas numpy a partir de listas de python!
lista = [1, 2, 3, 4, 5]
lista2 = [6, 7, 8, 9, 10]
lista_np = np.array(lista)
lista_np2 = np.array(lista2)

#### Operações 

In [111]:
# Multiplicação
lista_np * lista_np2

130

In [105]:
lista * 5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [119]:
lista_np

array([1, 2, 3, 4, 5])

In [106]:
lista_np * 5

array([ 5, 10, 15, 20, 25])

In [107]:
lista_np ** 2

array([ 1,  4,  9, 16, 25])

In [109]:
print(lista_np)
print(lista_np2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [282]:
import numpy as np

In [288]:
np.pi

3.141592653589793

In [290]:
np.sqrt(2)

1.4142135623730951

In [292]:
np.e

2.718281828459045

In [293]:
# log base natural (ln)
np.log(np.e)

1.0

v1 = [a, b, c]
v2 = [d, e, f]

produto_escalar = a * d + b * e + c * f

In [110]:
# Produto Escalar
np.dot(lista_np, lista_np2)

130

In [114]:
# Cria array de zeros!
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [116]:
# Cria array de uns!
uns = np.ones(10)
uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [122]:
# Cria array de um mesmo número
cincos = np.ones(10) * 5
cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [128]:
# Criando array com sequência
lista10 = np.arange(0, 10)
lista10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
# Criando array com sequência e um passo
lista10_2 = np.arange(0, 10, 0.1)
lista10_2

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [141]:
# Criando array de sequencia com número de pontos entre os limites!
# Linear Space
#.        min  max  # de pontos
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [146]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method


In [166]:
# Cria array aleatórios entre 0 e 1 de maneira uniforme!
aleatorio = np.random.rand(10)
aleatorio

array([0.15850349, 0.81718328, 0.46374617, 0.58084584, 0.63488213,
       0.75814205, 0.89005446, 0.99395095, 0.88405962, 0.03413648])

In [167]:
# Cria array aleatórios entre 0 e 10 de maneira uniforme!
aleatorio10 = np.random.rand(10) * 10
aleatorio10

array([9.00704226, 4.87625119, 4.12774501, 1.97530057, 8.61356252,
       3.73639712, 8.12887429, 3.40426764, 0.52896959, 1.57027844])

In [237]:
# Cria array de inteiros aleatórios
array1 = np.random.randint(1, 11, 10)
array1

array([ 7, 10,  2,  8,  5,  6,  6,  3,  7, 10])

In [217]:
# Gerar números aleatórios sem repetição!
np.random.choice(np.arange(1, 101), 10)

array([ 2, 33, 89, 81, 66,  4, 12, 70, 14, 93])

#### Indexação

In [178]:
lista1

array([ 5,  7,  5,  6,  2, 10,  5, 10,  5,  8])

In [177]:
lista1[0]

5

In [192]:
lista1[-1]

8

In [223]:
#   idx1 idx2 passo
lista1[1:10:2]

array([ 7,  6, 10, 10,  8])

### Métodos do numpy de arrays!

In [238]:
array1

array([ 7, 10,  2,  8,  5,  6,  6,  3,  7, 10])

In [243]:
array1.max()

10

In [247]:
array1.argmax()

1

In [244]:
array1.min()

2

In [248]:
array1.argmin()

2

In [241]:
array1.sum()

64

In [246]:
array1.mean()

6.4

In [249]:
array1.std()

2.4979991993593593

In [257]:
# Ordenação - operação inplace!
array1.sort()

In [264]:
print(array1)

[ 2  3  5  6  6  7  7  8 10 10]


In [270]:
array1.dtype

dtype('int64')

In [273]:
array1 = array1.astype(float)

In [274]:
print(array1)

[ 2.  3.  5.  6.  6.  7.  7.  8. 10. 10.]


In [275]:
array1.dtype

dtype('float64')

### Matrizes

In [378]:
listaD1 = np.linspace(0, 100, 20)
listaD2 = np.linspace(0, 50, 20)

In [379]:
listaD1

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [380]:
listaD2

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

In [381]:
listaD1 = listaD1.reshape(4, 5)
listaD2 = listaD2.reshape(4, 5)

In [382]:
listaD1

array([[  0.        ,   5.26315789,  10.52631579,  15.78947368,
         21.05263158],
       [ 26.31578947,  31.57894737,  36.84210526,  42.10526316,
         47.36842105],
       [ 52.63157895,  57.89473684,  63.15789474,  68.42105263,
         73.68421053],
       [ 78.94736842,  84.21052632,  89.47368421,  94.73684211,
        100.        ]])

In [383]:
listaD2

array([[ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579],
       [13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053],
       [26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526],
       [39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ]])

In [385]:
print(listaD1 * listaD2)

[[   0.           13.85041551   55.40166205  124.65373961  221.6066482 ]
 [ 346.26038781  498.61495845  678.67036011  886.4265928  1121.88365651]
 [1385.04155125 1675.90027701 1994.4598338  2340.72022161 2714.68144044]
 [3116.3434903  3545.70637119 4002.7700831  4487.53462604 5000.        ]]


In [314]:
# Reshape               m  n
matriz = listaD.reshape(3, 4)

In [315]:
matriz

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [386]:
# Matrizes a partir de listas!
listas = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [388]:
np.array(listas).shape

(3, 3)

In [391]:
# Matrizes identidade
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [395]:
# Matrizes de zeros
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [407]:
listaD1 = np.random.randint(1, 100, 30)
listaD1 = listaD1.reshape(6, 5)

In [408]:
print(listaD1)

[[97  3 59 27 95]
 [96 75 43 95  8]
 [93 90 41 26  1]
 [23 71 68 68 34]
 [ 8 95 81 10 45]
 [21  8 45 82 53]]


In [409]:
listaD1

array([[97,  3, 59, 27, 95],
       [96, 75, 43, 95,  8],
       [93, 90, 41, 26,  1],
       [23, 71, 68, 68, 34],
       [ 8, 95, 81, 10, 45],
       [21,  8, 45, 82, 53]])

In [ ]:
[90, 41, 26],
[71, 68, 68],
[95, 81, 10]

In [435]:
listaD1[2:6, 1:5]

array([[90, 41, 26,  1],
       [71, 68, 68, 34],
       [95, 81, 10, 45],
       [ 8, 45, 82, 53]])

In [437]:
listaD1[2:6, 1:5]

array([[90, 41, 26,  1],
       [71, 68, 68, 34],
       [95, 81, 10, 45],
       [ 8, 45, 82, 53]])

In [439]:
listaD1[2:6:2, 1:5]

array([[90, 41, 26,  1],
       [95, 81, 10, 45]])

In [441]:
listaD1[2:6:2, 1:5:2]

array([[90, 26],
       [95, 10]])

In [442]:
listaD1[3:5, 1:4]

array([[71, 68, 68],
       [95, 81, 10]])

---

#### Máscaras

Uma máscara é um array de verdadeiros e falsos que corresponde à alguma condição lógica. 

In [443]:
True

True

In [444]:
False

False

In [462]:
array = np.random.randint(1, 101, 20)

In [463]:
array

array([94, 44, 32, 82, 94, 91, 70, 40, 64, 58, 97, 74,  6, 93, 39, 78, 27,
       31, 51, 45])

In [464]:
# Máscara
mask = array < 50
print(mask)
menor_que_50 = array[mask]

[False  True  True False False False False  True False False False False
  True False  True False  True  True False  True]


In [483]:
maior_que_50 = array[array >= 50]

In [484]:
array[(array >= 90) | (array <= 10)]

array([94, 94, 91, 97,  6, 93])

In [485]:
# Exercício >= Pegar números pares de um array numpy!
array

array([94, 44, 32, 82, 94, 91, 70, 40, 64, 58, 97, 74,  6, 93, 39, 78, 27,
       31, 51, 45])

In [487]:
array[array % 2 == 0]

array([94, 44, 32, 82, 94, 70, 40, 64, 58, 74,  6, 78])

In [488]:
array % 2 == 0

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False,  True, False, False,
       False, False])

---