# Exercícios - NumPy

### Questão 1:

Dado o array:

```python
arr = np.arange(50)
```

Selecione a alternativa __INCORRETA__ na utilização de filtros e máscaras neste NumPy array, ou seja ao aplicarmos um filtro é esperado que seja devolvido uma lista com os números que satisfazem a condição do filtro.

__A)__ 
```python 
arr_atualizado  = arr[arr <= 10]
print(arr_atualizado)
```
__B)__
```python 
arr_atualizado  = arr[arr % 2]
print(arr_atualizado)
```
__C)__
```python 
arr_atualizado  = arr[(arr % 2 == 0) | (arr > 40)]
print(arr_atualizado)
```
__D)__
```python 
arr_atualizado  = arr[arr > 5]
print(arr_atualizado)
```

### RESPOSTA: ALTERNATIVA __B__

### Resolução:

Primeiramente, vamos definir a biblioteca e criar o array conforme o exemplo do exercício:

In [54]:
# Import do NumPy
import numpy as np

In [55]:
# Cria o array conforme o exercício
arr = np.arange(50)

# Print do array
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


Vamos testar todas as alternativas do exercício:

In [56]:
# Aplicação da máscara Booleana
arr_atualizado = arr[arr <= 10]

# Print do Array
print(arr_atualizado)

[ 0  1  2  3  4  5  6  7  8  9 10]


Aplicação correta da máscara booleana na alternativa A

In [57]:
# Aplicação da máscara booleana
arr_atualizado = arr[arr % 2]

# Print do Array
print(arr_atualizado)

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1]


Note que no exemplo da alternativa B, faltou a comparação do resto da divisão por 2 com algum valor para que funcionasse a máscara booleana! Da forma colocada pelo exercício, não funciona corretamente.

Se o objetivo fosse manter todos os números pares ou ímpares, os filtros deveriam ser feitos da seguinte forma:

In [58]:
# Aplicação da máscara booleana
arr_atualizado = arr[arr % 2 == 0]

# Print do Array
print("Apenas os números pares: ")
print(arr_atualizado)
print('\n')

# Aplicação da máscara booleana
print("Apenas os números ímpares: ")
arr_atualizado = arr[arr % 2 != 0]

# Print do Array
print(arr_atualizado)

Apenas os números pares: 
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


Apenas os números ímpares: 
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


Portanto a alternativa B é realmente a __incorreta__

Vamos testar agora a alternativa C:

In [59]:
# Aplicação da máscara booleana
arr_atualizado = arr[(arr % 2 == 0) | (arr > 40)]

# Print do Array
print(arr_atualizado)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 41 42 43
 44 45 46 47 48 49]


Vamos ver a aplicação dos filtros separadamente:

In [60]:
# Aplicação da máscara booleana - diferente de 3
mask1 = arr % 2 == 0

# Print da máscara booleana 1
print("Máscara Booleana - Diferente de 1: ")
print(mask1)
print('\n')

# Aplicação da máscara booleana - diferente de 3
mask2 = arr > 40

# Print da máscara booleana 2
print("Máscara Booleana - Diferente de 3: ")
print(mask2)
print('\n')

# Definição da máscara booleana 3
mask3 = mask1 | mask2

# Print da máscara booleana 3
print("Aplicação do OU entre as máscaras")
print(mask3)
print('\n')

# Filtro do array final
arr_final = arr[mask3]

# Print do Array
print('Array Final: ')
print(arr_final)

Máscara Booleana - Diferente de 1: 
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False]


Máscara Booleana - Diferente de 3: 
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True  True  True  True  True  True  True
  True  True]


Aplicação do OU entre as máscaras
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True  True  True  True  True  Tru

Então, a alternativa C também está correta.

Vamos testar a última alternativa:

In [61]:
# Aplicação do filtro
arr_atualizado = arr[arr > 5]

# Print do Array
print(arr_atualizado)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Esta aplicação é bem parecida com a primeira alternativa do exercício, onde queremos apenas os números maiores que 5. 
Portanto, a laternativa D também está correta.

## 

### Questão 2

Agora, vamos explorar os arrays aleatórios e máscaras. Faça o que se pede:

__A)__ Crie um array aleatório de 15 itens entre 0 e 100, incluindo os valores 0 e 100;

__B)__ Qual o maior número do array?

__C)__ Qual a sua posição?

__D)__ Verifique quais números do array são maior que 10;

__E)__ Salve em um novo array apenas os itens entre 10 e 30, incluindo os valores 10 e 30.

### Resolução:

Primeiramente, vamos definir a biblioteca:

In [9]:
# Import do NumPy
import numpy as np

__A)__ Crie um array aleatório de 15 itens entre 0 e 100, incluindo os valores 0 e 100;

In [10]:
# Definindo uma semente aleatória
np.random.seed(42)

# Criando um array de números inteiros entre 0 e 100 com 15 itens
arr = np.random.randint(low = 0,    # Limite inferior que deve conter os números
                        high = 101, # Limite superior (no caso 101, pois o último número é excludente)
                        size = 15)  # quantidade de elementos no array

# Print do Array
print(arr)

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21]


__B)__ Qual o maior número do array?

In [11]:
# Definindo o maior número utilizando a função np.max
maior = np.max(arr)

# Print do Array
print(maior)

99


__C)__ Qual a sua posição?

In [12]:
# Definindo a posição do maior elemento a partir da função argmax
idx_maior = np.argmax(arr)

# Print do index do maior elemento
print("Posição do maior elemento: ", idx_maior)

# Verificando se bate com o resultado anterior
print("Valor na posição de maior elemento: ", arr[idx_maior])

Posição do maior elemento:  11
Valor na posição de maior elemento:  99


__D)__ Verifique quais números do array são maior que 10;

In [13]:
# Filtrando o array apenas com os números maiores que 10
arr_maior_10 = arr[arr > 10]

# Print do Array
print(arr_maior_10)

[51 92 14 71 60 20 82 86 74 74 87 99 23 21]


__E)__ Salve em um novo array apenas os itens entre 10 e 30, incluindo os valores 10 e 30.

In [14]:
# Filtrando o array entre 10 e 30
novo_array = arr[(arr >= 10) & (arr <= 30)]

# Print do array
print(novo_array)

[14 20 23 21]


## 

### Questão 3

Nosso próximo foco serão as matrizes. Faça o que se pede:

__A)__ Utilizando o `np.linspace()`, crie um array de números entre 0 e 100 com 20 elementos;

__B)__ Converta o array do item __A)__ em uma matriz (10, 2) utilizando a função ``np.reshape``;

__C)__ Gere uma matriz aleatória de dimensão (2,5) com números entre 0 e 100, incluindo os números 0 e 100;

__D)__ Utilizando as matrizes do item __B)__ e __C)__, faça uma multiplicação de matrizes usando a função `np.dot`;

__Obs.:__ Atente-se a ordem das matrizes quando for realizar a multiplicação.

__E)__ Quais são as dimensões da matrizes resultante no item __D)__

### Resolução:

Primeiramente, vamos definir a biblioteca:

In [15]:
# Import do NumPy
import numpy as np

__A)__ Utilizando o `np.linspace()`, crie um array de números entre 0 e 100 com 20 elementos;

In [16]:
# Criando o array utilizando o linspace
arr = np.linspace(start = 0,  # número inicial
                  stop = 100, # número final
                  num = 20)   # quantidade de divisões

# Print do array
print(arr)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


__B)__ Converta o array do item __A)__ em uma matriz (10, 2) utilizando a função ``np.reshape``;

In [17]:
# Criando a matriz 1 a partir da função reshape
matrix1 = np.reshape(a = arr,            # array a ser redimensionado
                     newshape = (10, 2)) # nova dimensão do array resultante

# Print do Matriz
print(matrix1)

[[  0.           5.26315789]
 [ 10.52631579  15.78947368]
 [ 21.05263158  26.31578947]
 [ 31.57894737  36.84210526]
 [ 42.10526316  47.36842105]
 [ 52.63157895  57.89473684]
 [ 63.15789474  68.42105263]
 [ 73.68421053  78.94736842]
 [ 84.21052632  89.47368421]
 [ 94.73684211 100.        ]]


__C)__ Gere uma matriz aleatória de dimensão (2,5) com números entre 0 e 100, incluindo os números 0 e 100;

In [18]:
# Definindo uma semente aleatório
np.random.seed(42)

# Criando uma matriz 2 com números entre 0 e 100 e dimensões (2, 5)
matrix2 = np.random.randint(0, 101, size=(2, 5))

# Print da Matriz
print(matrix2)

[[51 92 14 71 60]
 [20 82 86 74 74]]


__D)__ Utilizando as matrizes do item __B)__ e __C)__, faça uma multiplicação de matrizes usando a função `np.dot`;

__Obs.:__ Atente-se a ordem das matrizes quando for realizar a multiplicação.

In [19]:
# Aplicando a multiplicação de matrizes usando np.dot
matrix3 = np.dot(matrix1, matrix2)

# Print da Matriz
print(matrix3)

[[  105.26315789   431.57894737   452.63157895   389.47368421
    389.47368421]
 [  852.63157895  2263.15789474  1505.26315789  1915.78947368
   1800.        ]
 [ 1600.          4094.73684211  2557.89473684  3442.10526316
   3210.52631579]
 [ 2347.36842105  5926.31578947  3610.52631579  4968.42105263
   4621.05263158]
 [ 3094.73684211  7757.89473684  4663.15789474  6494.73684211
   6031.57894737]
 [ 3842.10526316  9589.47368421  5715.78947368  8021.05263158
   7442.10526316]
 [ 4589.47368421 11421.05263158  6768.42105263  9547.36842105
   8852.63157895]
 [ 5336.84210526 13252.63157895  7821.05263158 11073.68421053
  10263.15789474]
 [ 6084.21052632 15084.21052632  8873.68421053 12600.
  11673.68421053]
 [ 6831.57894737 16915.78947368  9926.31578947 14126.31578947
  13084.21052632]]


__E)__ Quais são as dimensões da matrizes resultante no item __D)__

In [20]:
# Dimensão da matriz resultante
matrix3.shape

(10, 5)

## 

### Questão 4

Vamos praticar gerar matrizes e fazer operações com as linhas e colunas:

__A)__ Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica.:__ Utilize as funções `np.random.randint` e `np.reshape`

__B)__ Crie uma função que print os maiores valores de cada linha;

__C)__ Crie uma função que print os menores valores de cada coluna.

### Resolução:

Primeiramente, vamos importar a biblioteca do NumPy:

In [21]:
import numpy as np

__A)__ Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica.:__ Utilize as funções `np.random.randint` e `np.reshape`

In [63]:
# Define a semente aleatória
np.random.seed(42)

# Monta um vetor de 20 elementos com números aleatórios e depois faz um reshape (5,4)
A = np.random.randint(0, 51, 20).reshape(5, 4)

# Print da Matriz
print(A)

[[38 28 14 42]
 [ 7 20 38 18]
 [22 10 10 23]
 [35 39 23  2]
 [21  1 23 43]]


__B)__ Crie uma função que print os maiores valores de cada linha;

In [64]:
# Print do Texto
print("Os maiores valores por linha da matriz: ")

# Loop dos maiores números de cada linha
for i in range(A.shape[0]):
    print(np.max(A[i, :]))

Os maiores valores por linha da matriz: 
42
38
23
39
43


O mesmo pode ser feito com a função do _NumPy_ `np.amax`:

In [67]:
# Print do maior valor de cada coluna
print(np.amax(A, 1))

[42 38 23 39 43]


__C)__ Crie uma função que print os menores valores de cada coluna.

In [65]:
# Print do texto
print("Os menores valores por coluna da matriz: ")

# Loop dos menores números de cada linha
for i in range(A.shape[1]):
    print(np.min(A[:, i]))

Os menores valores por coluna da matriz: 
7
1
10
2


O mesmo pode ser feito utilizando a função do _NumPy_ `np.amin`:

In [66]:
# Print do menor valor de cada linha
print(np.amin(A, 0))

[ 7  1 10  2]


## 

### Questão 5

Vamos praticar o desenvolvimento de funções e operações com NumPy:

__A)__ Desenvolva uma função chamada `cria_matriz` que receba os parâmetros (a, b, m, rs), onde [a, b] são o intervalos para os números aleatórios (onde b > a), m vai ser a dimensão da matriz quadrada m x m e rs é o número da semente aleatória (caso não seja passado nenhum valor utilizar o `None`);

__B)__ Qual o resultado da multiplicação `cria_matriz(-6, 8, 4, 0)`*`cria_matriz(1, 50, 4, 0)`?

__Dica.:__ Utilize a função `np.dot` para a multiplicação de matrizes

### Resolução:

__A)__ Desenvolva uma função chamada `cria_matriz` que receba os parâmetros (a, b, m, rs), onde [a, b] são o intervalos para os números aleatórios (onde b > a), m vai ser a dimensão da matriz quadrada m x m e rs é o número da semente aleatória

In [70]:
# Cria a função que recebe (a, b, m, rs)
def cria_matriz(a, b, m, rs = None):
    # Define a semente aleatória
    np.random.seed(rs)
    # Testa a condição b > a
    if a >= b:
        print('o Valor de a é maior ou igual a b')
        return
    # Caso a condição seja satisfeita
    else:
        mtx = np.random.randint(a, b, m*m).reshape(m, m)
    # Cria o vetor de números aleatorios entre a e b, e faz o reshape para m x m
    return mtx

In [73]:
# Fazendo um teste para a função criada
matrix = cria_matriz(12, 38, 6, 0)

# Print da Matriz Resultante
print(matrix)

[[24 27 33 12 15 15]
 [19 21 31 33 30 16]
 [35 18 36 36 24 13]
 [18 19 35 26 36 29]
 [17 37 25 20 21 32]
 [31 28 31 17 27 27]]


__B)__ Qual o resultado da multiplicação `cria_matiz(-6, 8, 4, 0)`*`cria_matiz(1, 50, 4, 0)`?

__Dica.:__ Utilize a função `np.dot` para a multiplicação de matrizes

Para resolver este exercícios, vamos dividir em duas partes:
- Criar as matrizes que vão ser multiplicadas;
- Fazer a multiplicação de matrizes

Vamos primeiro criar as matrizes:

In [27]:
# Criando a matriz A
A = cria_matriz(-6, 8, 4, 0)

# Print da Matriz
print(A)

[[ 6 -1 -6 -3]
 [ 5 -3  1  3]
 [-3 -1 -4 -2]
 [ 1  0  2  2]]


In [28]:
# Criando a matriz B
B = cria_matriz(1, 50, 4, 0)

#Print da Matriz
print(B)

[[45 48  1  4]
 [ 4 40 10 20]
 [22 37 24  7]
 [25 25 13  2]]


In [29]:
# Calcula a multiplicação de matriz entre A e B
C = np.dot(A, B)

# Print da Matriz da Resultante
print(C)

[[  59  -49 -187  -44]
 [ 310  232   38  -27]
 [-277 -382 -135  -64]
 [ 139  172   75   22]]


## 

### Questão 6

Criar uma Matriz (10, 2) onde a primeira coluna tenham números de 1 a 10 e a segunda coluna esteja preenchida somente com zeros

### Resolução:

Primeiramente carregando a biblioteca do _NumPy_:

In [77]:
import numpy as np

Podemos resolver esse exercício de algumas formas diferentes:

In [30]:
col1 = np.arange(1, 11)
col1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Utilizando a função `np.vstack`:

In [74]:
# Resolvendo utilizando o vstack
print(np.vstack((col1, np.zeros(10))).T)

[[ 1.  0.]
 [ 2.  0.]
 [ 3.  0.]
 [ 4.  0.]
 [ 5.  0.]
 [ 6.  0.]
 [ 7.  0.]
 [ 8.  0.]
 [ 9.  0.]
 [10.  0.]]


Utilizando a função `np.hstack`:

In [75]:
# Resolvendo utilizando o hstack
print(np.hstack((col1.reshape(10, 1), np.zeros((10, 1)))))

[[ 1.  0.]
 [ 2.  0.]
 [ 3.  0.]
 [ 4.  0.]
 [ 5.  0.]
 [ 6.  0.]
 [ 7.  0.]
 [ 8.  0.]
 [ 9.  0.]
 [10.  0.]]


Utilizando a função `np.concatanate`:

In [33]:
# Utilizando o np.concatanate
print(np.concatenate((col1.reshape(10,1), np.zeros((10,1))), axis=1))

array([[ 1.,  0.],
       [ 2.,  0.],
       [ 3.,  0.],
       [ 4.,  0.],
       [ 5.,  0.],
       [ 6.,  0.],
       [ 7.,  0.],
       [ 8.,  0.],
       [ 9.,  0.],
       [10.,  0.]])

Utilizando Loop e listas:

In [76]:
# Cria uma lista vazia
lista = []

# loop para criar os números
for i in range(1, 11):
    lista.append([i, 0])
    
# Print da lista
print(np.array(lista))

[[ 1  0]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 5  0]
 [ 6  0]
 [ 7  0]
 [ 8  0]
 [ 9  0]
 [10  0]]


## 

### Questão 7

Vamos praticar o uso de Slices em Numpy Arrays:

__A)__ Crie um array com 20 números sequenciais

__B)__ Crie um slice que selecione somente as posições pares do array (0, 2, 4, 6, 8, ...)

__C)__ Crie um slice que selecione somente as posições impares do array (1, 3, 5, 7, 9, ...)

__D)__ Crie um slice que selecione do 5 ao 10 elemento

__E)__ Crie um slice que inverta o array

__F)__ Crie um slice inverte somente os dois ultimos elementos e retorna uma lista com 2 elementos

### Resolução

Primeiramente, vamos carregar a biblioteca do _NumPy_:

In [78]:
import numpy as np

__A)__ Crie um array com 20 números sequenciais


In [79]:
# Cria o array
arr = np.arange(20)

# Print do Array
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]



__B)__ Crie um slice que selecione somente as posições pares do array (0, 2, 4, 6, 8, ...)

In [80]:
# Print do Slice
print(arr[::2])

[ 0  2  4  6  8 10 12 14 16 18]


__C)__ Crie um slice que selecione somente as posições impares do array (1, 3, 5, 7, 9, ...)


In [81]:
# Print do Slice
print(arr[1::2])

[ 1  3  5  7  9 11 13 15 17 19]


__D)__ Crie um slice que selecione do 5 ao 10 elemento


In [82]:
# Print do Slice
print(arr[4:10])

[4 5 6 7 8 9]



__D)__ Crie um slice que inverta o array


In [83]:
# Print do Slice
print(arr[::-1])

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]



__E)__ Crie um slice inverte somente os dois ultimos elementos e retorna uma lista com 2 elementos

In [84]:
# Print do Slice
print(arr[:-3:-1])

[19 18]
