In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
v = np.arange(-10, 10)
u = np.arange(-10, 10)
v

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [6]:
l2 = np.sqrt(v**2)
l2


array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.,  1.,  2.,
        3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [5]:
l1 = np.abs(v)
l1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [14]:
u = np.array([-25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
u


array([-25,   2,   5])

In [15]:
np.max(np.abs(u))

25

In [16]:
np.linalg.norm(u, np.inf)

25.0